In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras as kr
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
import sklearn

In [41]:
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  except RuntimeError as e:
    print(e)

In [64]:
data = pd.read_csv('NFT_DATASET1.csv')

In [65]:
data=data.values
data

array([['N1', 25.0, 40.0, 10.0, 70.0, 60.0, 20.0, 20.0, 32, 36, 43, 38,
        41, 45, 36, 41, 48, 45, 70.0, 20.0, 80.0, 40.0, 45.0, 44.0],
       ['N2', 42.0, 22.0, 27.0, 35.0, 19.0, 68.0, 52.0, 71, 71, 72, 64,
        71, 70, 68, 63, 64, 67, 56.0, 87.0, 76.0, 60.0, 70.0, 62.0],
       ['N3', 35.0, 91.0, 28.0, 70.0, 63.0, 31.0, 45.0, 14, 13, 11, 12,
        12, 15, 11, 12, 13, 11, 45.0, 42.0, 89.0, 73.0, 12.0, 12.0],
       ['N4', 12.0, 56.0, 18.0, 89.0, 94.0, 13.0, 10.0, 12, 11, 9, 11,
        11, 12, 10, 12, 10, 10, 23.0, 54.0, 78.0, 77.0, 9.0, 9.0],
       ['N5', 34.0, 73.0, 57.0, 61.0, 93.0, 57.0, 71.0, 99, 93, 97, 98,
        93, 94, 96, 100, 94, 91, 68.0, 23.0, 31.0, 92.0, 97.0, 98.0],
       ['N6', 54.0, 31.0, 19.0, 11.0, 14.0, 60.0, 60.0, 21, 21, 22, 20,
        20, 22, 21, 20, 22, 21, 89.0, 60.0, 42.0, 39.0, 21.0, 20.0],
       ['N7', 70.0, 65.0, 48.0, 56.0, 89.0, 68.0, 40.0, 45, 44, 43, 43,
        44, 44, 43, 45, 43, 45, 12.0, 64.0, 80.0, 74.0, 43.0, 45.0],
       ['N8', 3

In [66]:
X_train = data[:10,8:18]
X_test = data[10:,8:18]
Y_train = data[:10,23]
Y_test = data[10:,23]

In [67]:
X_train

array([[32, 36, 43, 38, 41, 45, 36, 41, 48, 45],
       [71, 71, 72, 64, 71, 70, 68, 63, 64, 67],
       [14, 13, 11, 12, 12, 15, 11, 12, 13, 11],
       [12, 11, 9, 11, 11, 12, 10, 12, 10, 10],
       [99, 93, 97, 98, 93, 94, 96, 100, 94, 91],
       [21, 21, 22, 20, 20, 22, 21, 20, 22, 21],
       [45, 44, 43, 43, 44, 44, 43, 45, 43, 45],
       [17, 15, 16, 16, 16, 16, 17, 15, 17, 15],
       [75, 76, 76, 76, 76, 75, 76, 75, 75, 76],
       [51, 50, 51, 51, 48, 49, 49, 49, 49, 49]], dtype=object)

In [68]:
Y_train

array([44.0, 62.0, 12.0, 9.0, 98.0, 20.0, 45.0, 15.0, 78.0, 53.0],
      dtype=object)

In [69]:
X_test

array([[3, 5, 6, 8, 7, 5, 8, 10, 11, 12],
       [2, 7, 8, 10, 7, 4, 5, 10, 15, 16],
       [20, 23, 25, 21, 26, 32, 36, 34, 33, 38],
       [15, 20, 23, 29, 36, 42, 39, 35, 29, 47],
       [10, 12, 13, 9, 7, 8, 10, 12, 15, 13],
       [15, 17, 13, 15, 14, 18, 20, 15, 10, 7],
       [1, 3, 4, 2, 4, 5, 6, 2, 3, 4]], dtype=object)

In [70]:
Y_test

array([nan, nan, nan, nan, nan, nan, nan], dtype=object)

In [71]:
train_data = np.asarray(X_train).astype('float32')
train_label = np.asarray(Y_train).astype('float32')

print(np.shape(train_data))

(10, 10)


In [55]:
model = kr.Sequential([
    kr.layers.Dense(10, activation='relu', input_shape = (10,)),
    kr.layers.Dense(10, activation='relu'),
    kr.layers.Dense(10, activation='relu'),
    kr.layers.Dense(2, activation='softmax', name='output')
])

# model.compile(optimizer='SGD', loss= 'categorical_crossentropy', metrics=["accuracy"])
model.compile(optimizer='SGD', loss= 'BinaryCrossentropy', metrics=["accuracy"])

In [39]:
model.fit(train_data, train_label, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 10.1541 - accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 587us/step - loss: 9.4471 - accuracy: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 555us/step - loss: 7.0820 - accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 573us/step - loss: 5.4309 - accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 548us/step - loss: 3.2764 - accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 644us/step - loss: 2.4786 - accuracy: 0.0000e+00
Epoch 7/100
1/1 [==============================] - 0s 579us/step - loss: 8.7742 - accuracy: 0.0000e+00
Epoch 8/100
1/1 [==============================] - 0s 542us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 9/100
1/1 [==============================] - 0s 739us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 10/100
1/1 [==============================] - 0s 595us/step - loss

1/1 [==============================] - 0s 1000us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 80/100
1/1 [==============================] - 0s 1ms/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 81/100
1/1 [==============================] - 0s 664us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 82/100
1/1 [==============================] - 0s 779us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 83/100
1/1 [==============================] - 0s 1ms/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 84/100
1/1 [==============================] - 0s 1ms/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 85/100
1/1 [==============================] - 0s 2ms/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 86/100
1/1 [==============================] - 0s 640us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 87/100
1/1 [==============================] - 0s 840us/step - loss: 11.2643 - accuracy: 0.0000e+00
Epoch 88/100
1/1 [==============================] - 0s 1ms/step - loss: 11.

In [72]:
from sklearn.linear_model import LinearRegression

In [73]:
mod = LinearRegression()

In [74]:
mod.fit(train_data,train_label)

LinearRegression()

In [75]:
mod.predict(X_test)

array([10.41454572, 21.1406041 , 19.65937909, 17.97427639, 14.58561906,
       -2.16487097, -4.52771763])